spring.application.name=TestTitle
spring.datasource.url=jdbc:postgresql://localhost:60811/eclipsedb
spring.datasource.username=myeclipse
spring.datasource.password=secreteclipse
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=1010

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
app.upload.dir=uploads

app.admin.username=admin
app.admin.password=admin123
app.admin.email=admin@example.com