spring.application.name=TestTitle
spring.datasource.url=jdbc:postgresql://localhost:5432/eclipsedb
spring.datasource.username=myeclipse
spring.datasource.password=secreteclipse
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=1010

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
app.upload.dir=uploads