-- Privacy settings and block list (V12)

ALTER TABLE public.users ADD COLUMN hide_online_status BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.users ADD COLUMN searchable BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE public.users ADD COLUMN messages_from VARCHAR(20) NOT NULL DEFAULT 'ALL';
ALTER TABLE public.users ADD CONSTRAINT users_messages_from_check CHECK (((messages_from)::text = ANY ((ARRAY['ALL'::character varying, 'KNOWN_ONLY'::character varying])::text[])));

CREATE TABLE public.user_blocks (
    id BIGINT NOT NULL,
    blocker_username VARCHAR(255) NOT NULL,
    blocked_username VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT user_blocks_pkey PRIMARY KEY (id),
    CONSTRAINT uq_user_blocks_pair UNIQUE (blocker_username, blocked_username)
);

CREATE INDEX idx_user_blocks_blocker ON public.user_blocks (blocker_username);
CREATE INDEX idx_user_blocks_blocked ON public.user_blocks (blocked_username);

ALTER TABLE public.user_blocks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_blocks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
