-- ShadowVibe baseline schema (Flyway V1)
-- Generated from live DB created by Hibernate ddl-auto=update.


-- Name: chat_group_members; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.chat_group_members (
    group_id bigint NOT NULL,
    user_id bigint NOT NULL
);

-- Name: chat_groups; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.chat_groups (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    name character varying(100) NOT NULL,
    created_by_id bigint NOT NULL,
    avatar_filename character varying(255)
);

-- Name: chat_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.chat_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: group_memberships; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.group_memberships (
    id bigint NOT NULL,
    last_read_at timestamp(6) without time zone,
    group_id bigint NOT NULL,
    user_id bigint NOT NULL
);

-- Name: group_memberships_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.group_memberships ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.group_memberships_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: group_message_deletions; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.group_message_deletions (
    message_id bigint NOT NULL,
    user_id bigint NOT NULL
);

-- Name: group_messages; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.group_messages (
    id bigint NOT NULL,
    content character varying(2000) NOT NULL,
    sent_at timestamp(6) without time zone NOT NULL,
    group_id bigint NOT NULL,
    sender_id bigint NOT NULL,
    attachment_filename character varying(255),
    attachment_original_name character varying(255),
    attachment_size bigint,
    attachment_type character varying(255),
    reply_to_id bigint,
    reply_to_content character varying(200),
    reply_to_sender character varying(255),
    sticker_code character varying(80),
    sticker_url character varying(255)
);

-- Name: group_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.group_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.group_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: message; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.message (
    id bigint NOT NULL,
    content character varying(2000),
    read_at timestamp(6) without time zone,
    "time" timestamp(6) without time zone,
    receiver_id bigint NOT NULL,
    sender_id bigint NOT NULL,
    attachment_filename character varying(255),
    attachment_original_name character varying(255),
    attachment_size bigint,
    attachment_type character varying(255),
    reply_to_id bigint,
    reply_to_content character varying(200),
    reply_to_sender character varying(255),
    deleted_by_sender boolean DEFAULT false,
    deleted_by_receiver boolean DEFAULT false,
    sticker_code character varying(80),
    sticker_url character varying(255),
    audio_url character varying(500)
);

-- Name: message_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: sticker_packs; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.sticker_packs (
    id bigint NOT NULL,
    author_username character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    name character varying(60) NOT NULL
);

-- Name: sticker_packs_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.sticker_packs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sticker_packs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: stickers; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.stickers (
    id bigint NOT NULL,
    code character varying(80) NOT NULL,
    filename character varying(255) NOT NULL,
    pack_id bigint NOT NULL
);

-- Name: stickers_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.stickers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stickers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: user_sticker_packs; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.user_sticker_packs (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    pack_id bigint NOT NULL,
    user_id bigint NOT NULL
);

-- Name: user_sticker_packs_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.user_sticker_packs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_sticker_packs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: users; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.users (
    id bigint NOT NULL,
    about character varying(500),
    avatar_filename character varying(255),
    password character varying(255) NOT NULL,
    role smallint NOT NULL,
    theme_preference character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    email character varying(255),
    vk_token character varying(512),
    CONSTRAINT users_role_check CHECK (((role >= 0) AND (role <= 1))),
    CONSTRAINT users_theme_preference_check CHECK (((theme_preference)::text = ANY ((ARRAY['DARK'::character varying, 'LIGHT'::character varying])::text[])))
);

-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: watch_room_members; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.watch_room_members (
    room_id bigint NOT NULL,
    user_id bigint NOT NULL
);

-- Name: watch_room_messages; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.watch_room_messages (
    id bigint NOT NULL,
    content character varying(2000) NOT NULL,
    sent_at timestamp(6) without time zone NOT NULL,
    room_id bigint NOT NULL,
    sender_id bigint NOT NULL,
    sticker_code character varying(80),
    sticker_url character varying(255),
    audio_url character varying(500),
    audio_duration_ms bigint
);

-- Name: watch_room_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.watch_room_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.watch_room_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: watch_room_playlist_items; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.watch_room_playlist_items (
    id bigint NOT NULL,
    added_by character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    "position" integer NOT NULL,
    title character varying(300),
    video_url character varying(2000) NOT NULL,
    room_id bigint NOT NULL
);

-- Name: watch_room_playlist_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.watch_room_playlist_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.watch_room_playlist_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: watch_rooms; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.watch_rooms (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    host_username character varying(255) NOT NULL,
    name character varying(100) NOT NULL,
    position_ms bigint NOT NULL,
    room_code character varying(12) NOT NULL,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    video_url character varying(2000),
    current_item_id bigint,
    visibility character varying(255) DEFAULT 'PUBLIC'::character varying NOT NULL,
    video_thumb character varying(2000),
    video_title character varying(300),
    CONSTRAINT watch_rooms_status_check CHECK (((status)::text = ANY ((ARRAY['IDLE'::character varying, 'PLAYING'::character varying, 'PAUSED'::character varying])::text[]))),
    CONSTRAINT watch_rooms_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['PUBLIC'::character varying, 'PRIVATE'::character varying])::text[])))
);

-- Name: watch_rooms_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.watch_rooms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.watch_rooms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: chat_group_members chat_group_members_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.chat_group_members
    ADD CONSTRAINT chat_group_members_pkey PRIMARY KEY (group_id, user_id);

-- Name: chat_groups chat_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.chat_groups
    ADD CONSTRAINT chat_groups_pkey PRIMARY KEY (id);

-- Name: group_memberships group_memberships_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.group_memberships
    ADD CONSTRAINT group_memberships_pkey PRIMARY KEY (id);

-- Name: group_message_deletions group_message_deletions_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.group_message_deletions
    ADD CONSTRAINT group_message_deletions_pkey PRIMARY KEY (message_id, user_id);

-- Name: group_messages group_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.group_messages
    ADD CONSTRAINT group_messages_pkey PRIMARY KEY (id);

-- Name: message message_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.message
    ADD CONSTRAINT message_pkey PRIMARY KEY (id);

-- Name: sticker_packs sticker_packs_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.sticker_packs
    ADD CONSTRAINT sticker_packs_pkey PRIMARY KEY (id);

-- Name: stickers stickers_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.stickers
    ADD CONSTRAINT stickers_pkey PRIMARY KEY (id);

-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

-- Name: group_memberships uk9av1qwqwmki0a1whrqvi26t8t; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.group_memberships
    ADD CONSTRAINT uk9av1qwqwmki0a1whrqvi26t8t UNIQUE (group_id, user_id);

-- Name: user_sticker_packs ukduqqhbigdhjywmtg4h87luugx; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.user_sticker_packs
    ADD CONSTRAINT ukduqqhbigdhjywmtg4h87luugx UNIQUE (user_id, pack_id);

-- Name: sticker_packs ukgtqvaisn2kg9jh7ux97dqlde; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.sticker_packs
    ADD CONSTRAINT ukgtqvaisn2kg9jh7ux97dqlde UNIQUE (name);

-- Name: watch_rooms ukjp9s9khnsoc6d267dqr7oqdx; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.watch_rooms
    ADD CONSTRAINT ukjp9s9khnsoc6d267dqr7oqdx UNIQUE (room_code);

-- Name: stickers ukp3eup5juadx2dvu08yt1eycjm; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.stickers
    ADD CONSTRAINT ukp3eup5juadx2dvu08yt1eycjm UNIQUE (code);

-- Name: group_message_deletions ukswrqs36uirrauw7fq3rjvju98; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.group_message_deletions
    ADD CONSTRAINT ukswrqs36uirrauw7fq3rjvju98 UNIQUE (message_id, user_id);

-- Name: user_sticker_packs user_sticker_packs_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.user_sticker_packs
    ADD CONSTRAINT user_sticker_packs_pkey PRIMARY KEY (id);

-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

-- Name: watch_room_members watch_room_members_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.watch_room_members
    ADD CONSTRAINT watch_room_members_pkey PRIMARY KEY (room_id, user_id);

-- Name: watch_room_messages watch_room_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.watch_room_messages
    ADD CONSTRAINT watch_room_messages_pkey PRIMARY KEY (id);

-- Name: watch_room_playlist_items watch_room_playlist_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.watch_room_playlist_items
    ADD CONSTRAINT watch_room_playlist_items_pkey PRIMARY KEY (id);

-- Name: watch_rooms watch_rooms_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.watch_rooms
    ADD CONSTRAINT watch_rooms_pkey PRIMARY KEY (id);

-- Name: group_messages fk1eabq9qdyvxhpnrxj6ngs2vmx; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.group_messages
    ADD CONSTRAINT fk1eabq9qdyvxhpnrxj6ngs2vmx FOREIGN KEY (group_id) REFERENCES public.chat_groups(id);

-- Name: user_sticker_packs fk5o0na2s3eqyqyfhn4w0f341mg; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.user_sticker_packs
    ADD CONSTRAINT fk5o0na2s3eqyqyfhn4w0f341mg FOREIGN KEY (user_id) REFERENCES public.users(id);

-- Name: message fk9a25x9o5r7wguarxeon2a9tmr; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.message
    ADD CONSTRAINT fk9a25x9o5r7wguarxeon2a9tmr FOREIGN KEY (receiver_id) REFERENCES public.users(id);

-- Name: group_memberships fk9w8n5obdanaqf6en870bu2ham; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.group_memberships
    ADD CONSTRAINT fk9w8n5obdanaqf6en870bu2ham FOREIGN KEY (group_id) REFERENCES public.chat_groups(id);

-- Name: message fkbi5avhe69aol2mb1lnm6r4o2p; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.message
    ADD CONSTRAINT fkbi5avhe69aol2mb1lnm6r4o2p FOREIGN KEY (sender_id) REFERENCES public.users(id);

-- Name: group_messages fkcuf7bhtxj1qc0ajswsjrn9vvd; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.group_messages
    ADD CONSTRAINT fkcuf7bhtxj1qc0ajswsjrn9vvd FOREIGN KEY (sender_id) REFERENCES public.users(id);

-- Name: chat_group_members fkewjk3724m9ci5f5ynd8k8b16k; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.chat_group_members
    ADD CONSTRAINT fkewjk3724m9ci5f5ynd8k8b16k FOREIGN KEY (user_id) REFERENCES public.users(id);

-- Name: watch_room_members fklbccvul9sgjryrr5n9nvht72w; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.watch_room_members
    ADD CONSTRAINT fklbccvul9sgjryrr5n9nvht72w FOREIGN KEY (room_id) REFERENCES public.watch_rooms(id);

-- Name: group_memberships fklq7o99bv8w6paut0ih5yhboia; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.group_memberships
    ADD CONSTRAINT fklq7o99bv8w6paut0ih5yhboia FOREIGN KEY (user_id) REFERENCES public.users(id);

-- Name: watch_room_playlist_items fkmgftllyimgwphi5qiaye41vkm; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.watch_room_playlist_items
    ADD CONSTRAINT fkmgftllyimgwphi5qiaye41vkm FOREIGN KEY (room_id) REFERENCES public.watch_rooms(id);

-- Name: chat_group_members fkni2vmtvcofelbn60q5vfcncd0; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.chat_group_members
    ADD CONSTRAINT fkni2vmtvcofelbn60q5vfcncd0 FOREIGN KEY (group_id) REFERENCES public.chat_groups(id);

-- Name: watch_room_messages fko5bne4k6k2acd7l2t69j8f3ul; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.watch_room_messages
    ADD CONSTRAINT fko5bne4k6k2acd7l2t69j8f3ul FOREIGN KEY (sender_id) REFERENCES public.users(id);

-- Name: watch_room_members fkpqvivf5uhf01nlvrf7vc42rae; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.watch_room_members
    ADD CONSTRAINT fkpqvivf5uhf01nlvrf7vc42rae FOREIGN KEY (user_id) REFERENCES public.users(id);

-- Name: watch_room_messages fkrihrctqqnt04iwqot0disap7l; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.watch_room_messages
    ADD CONSTRAINT fkrihrctqqnt04iwqot0disap7l FOREIGN KEY (room_id) REFERENCES public.watch_rooms(id);

-- Name: stickers fksdc800900parrg65pk69cep74; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.stickers
    ADD CONSTRAINT fksdc800900parrg65pk69cep74 FOREIGN KEY (pack_id) REFERENCES public.sticker_packs(id);

-- Name: chat_groups fksm7knvk2vdobxuck5q616v16i; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.chat_groups
    ADD CONSTRAINT fksm7knvk2vdobxuck5q616v16i FOREIGN KEY (created_by_id) REFERENCES public.users(id);

-- Name: user_sticker_packs fkt5y8sfri4wlken82vi6hnoyj4; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.user_sticker_packs
    ADD CONSTRAINT fkt5y8sfri4wlken82vi6hnoyj4 FOREIGN KEY (pack_id) REFERENCES public.sticker_packs(id);

-- Name: group_message_deletions group_message_deletions_message_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.group_message_deletions
    ADD CONSTRAINT group_message_deletions_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.group_messages(id) ON DELETE CASCADE;

-- Name: group_message_deletions group_message_deletions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.group_message_deletions
    ADD CONSTRAINT group_message_deletions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

