-- ShadowVibe reactions on messages (V2)
-- One table for all chat types (DIRECT / GROUP / WATCH)

CREATE TABLE public.message_reactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_type character varying(20) NOT NULL,
    message_id bigint NOT NULL,
    user_id bigint NOT NULL,
    emoji character varying(32) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT message_reactions_uk UNIQUE (message_type, message_id, user_id, emoji)
);
