-- ShadowVibe web push subscriptions (V4)

CREATE TABLE public.push_subscription (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    endpoint varchar(2048) NOT NULL,
    p256dh varchar(512) NOT NULL,
    auth varchar(256) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT push_subscription_uk UNIQUE (user_id, endpoint)
);
