-- ShadowVibe per-chat notification mutes (V6)

CREATE TABLE public.chat_mutes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    partner_id bigint NOT NULL,
    muted boolean NOT NULL DEFAULT false,
    created_at timestamp(6) without time zone NOT NULL DEFAULT now(),
    CONSTRAINT chat_mutes_uk UNIQUE (user_id, partner_id)
);

ALTER TABLE public.group_memberships ADD COLUMN muted boolean NOT NULL DEFAULT false;
